## 🚨 异常类

#### 🔗 Kotlin 中所有异常类继承自 `Throwable` 类。

📊 每个异常都有消息、堆栈回溯信息以及可选的原因。

#### 🚀 使用 `throw` 表达式来抛出异常：

```kotlin
fun main() {
//sampleStart
    throw Exception("Hi There!")
//sampleEnd
}
```

#### 🛡️ 使用 `try`……`catch` 表达式来捕获异常：

```kotlin
try {
    // 一些代码
} catch (e: SomeException) {
    // 处理程序
} finally {
    // 可选的 finally 块
}
```

> 🔢 可以有零到多个 `catch` 块，`finally` 块可以省略。

> ⚠️ 但是 `catch` 与 `finally` 块至少需有一个。